### ISSUE TITLE
Lens: Add option to draw focal point only on one side

### ISSUE THREAD

**Issue by genodeftest** [fruchart/tikz-optics#4]
Currently, focal points have to be drawn on both sides or not at all. It would be nice to have them drawn on one side only.

**Comment by fruchart** [comment]
I have to think about it, it would be easy but I am not sure that even the `draw focal points` style is a good idea (it is not so easy to customize, and is mainly there as a shortcut).
But you can use


```latex
\begin{tikzpicture}[use optics]
\node[lens] (L) at (0,0) {};

\node[optics/mark a cross] at (L.west focal point) {};
\end{tikzpicture}
```


to get
![west_focal_point](https://user-images.githubusercontent.com/13440379/31301880-af1e3548-aafd-11e7-8496-11bad4b8430c.png)

Indeed, the same works with `east focal point`, and any shape instead of `optics/mark a cross`.

**Comment by genodeftest** [comment]
Ok, that's not more code than using the "draw focal points", so this solution is surely good enough.
